/* Chat */
export const CHAT_APPEND_HISTORY = "CHAT_APPEND_HISTORY";
/* Chat Input Box */
export const CHAT_INPUT_BOX_FOCUS = "CHAT_INPUT_BOX_FOCUS";
export const CHAT_INPUT_BOX_KEYSTROKE = "CHAT_INPUT_BOX_KEYSTROKE";
export const CHAT_INPUT_BOX_UPDATE_CONTENTS = "CHAT_INPUT_BOX_UPDATE_CONTENTS";
/* Inventory */
export const INVENTORY_TOGGLE_VIEW = "INVENTORY_TOGGLE_VIEW";
export const INVENTORY_UPDATE = "INVENTORY_UPDATE";
