/* Chat History */
export const APPEND_CHAT_HISTORY = "APPEND_CHAT_HISTORY";
/* Chat Input Box */
export const FOCUS_CHAT_INPUT_BOX = "FOCUS_CHAT_INPUT_BOX";
export const CHAT_INPUT_BOX_KEYSTROKE = "CHAT_INPUT_BOX_KEYSTROKE"
export const CHAT_INPUT_BOX_UPDATE_CONTENTS = "CHAT_INPUT_BOX_UPDATE_CONTENTS"