/* Chat */
export const CHAT_APPEND_HISTORY = "CHAT_APPEND_HISTORY";
/* Chat Input Box */
export const CHAT_INPUT_BOX_FOCUS = "CHAT_INPUT_BOX_FOCUS";
export const CHAT_INPUT_BOX_KEYSTROKE = "CHAT_INPUT_BOX_KEYSTROKE";
export const CHAT_INPUT_BOX_UPDATE_CONTENTS = "CHAT_INPUT_BOX_UPDATE_CONTENTS";
/* Inventory */
export const INVENTORY_TOGGLE_VIEW = "INVENTORY_TOGGLE_VIEW";
export const INVENTORY_UPDATE = "INVENTORY_UPDATE";
/* Notification */
export const NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE";
/* HUD */
export const HUD_UPDATE_CURRENT_HP = "HUD_UPDATE_CURRENT_HP";
export const HUD_UPDATE_CURRENT_MP = "HUD_UPDATE_CURRENT_MP";
export const HUD_UPDATE_CURRENT_XP = "HUD_UPDATE_CURRENT_XP";
export const HUD_UPDATE_MAX_HP = "HUD_UPDATE_MAX_HP";
export const HUD_UPDATE_MAX_MP = "HUD_UPDATE_MAX_MP";
export const HUD_UPDATE_MAX_XP = "HUD_UPDATE_MAX_XP";
export const HUD_UPDATE_LEVEL = "HUD_UPDATE_LEVEL";