import { AnimationComponent } from "../components/animation";
import { NameplateComponent } from "../components/nameplate";
import { PositionComponent } from "../components/position";
import { SpriteComponent } from "../components/sprite";
import { PlayerComponent } from "../components/player";

export class ClientEntity {
    public netId: number; // Number generated by back end to associate client represented entities to their back-end counterparts.
    public parentNetId: number;
    public pos: PositionComponent;
    public anim: AnimationComponent;
    public sprite: SpriteComponent;
    public player: PlayerComponent;
    public nameplate: NameplateComponent;
}