export enum ClientInputTypes {
    ATTACK = "ATTACK",
    LEFT_KEY_DOWN = "LEFT_KEY_DOWN",
    LEFT_KEY_UP = "LEFT_KEY_UP",
    RIGHT_KEY_DOWN = "RIGHT_KEY_DOWN",
    RIGHT_KEY_UP = "RIGHT_KEY_UP",
    UP_KEY_UP = "UP_KEY_UP",
    UP_KEY_DOWN = "UP_KEY_DOWN",
    DOWN_KEY_UP = "DOWN_KEY_UP",
    DOWN_KEY_DOWN = "DOWN_KEY_DOWN",
}