export enum ClientEventTypes {
    PLAYER_JOINED = "PLAYER_JOINED",
    SPECTATOR_JOINED = "SPECTATOR_JOINED",
    LEFT_KEY_DOWN = "LEFT_KEY_DOWN",
    LEFT_KEY_UP = "LEFT_KEY_UP",
    RIGHT_KEY_DOWN = "RIGHT_KEY_DOWN",
    RIGHT_KEY_UP = "RIGHT_KEY_UP",
    INPUT_TO_QUERY = "INPUT_TO_QUERY"
}