export enum MessageTypes {
    CLIENT_EVENT_MESSAGE = "CLIENT_EVENT_MESSAGE",
    CLIENT_INPUT_MESSAGE = "CLIENT_INPUT_MESSAGE",
    NET_ENTITY_MESSAGE = "NET_ENTITY_MESSAGE",
    NET_EVENT_MESSAGE = "NET_EVENT_MESSAGE",
    NET_WORLD_MESSAGE = "NET_WORLD_MESSAGE",
}