export enum MessageTypes {
    ENTITY_MESSAGE = "ENTITY_MESSAGE",
    CLIENT_EVENT_MESSAGE = "CLIENT_EVENT_MESSAGE",
    CLIENT_INPUT_MESSAGE = "CLIENT_INPUT_MESSAGE",
    NET_EVENT_MESSAGE = "NET_EVENT_MESSAGE",
}